/**
 * recover_from_pdf.mjs
 * Recupera clientes do relatório PDF exportado em 31/03/2026.
 * Uso: node recover_from_pdf.mjs
 */
import pg from 'pg'
import { readFile } from 'fs/promises'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dir = dirname(fileURLToPath(import.meta.url))
const envText = await readFile(join(__dir, '.env'), 'utf8').catch(() => '')
for (const line of envText.split('\n')) {
  const [k, ...rest] = line.trim().split('=')
  if (k && rest.length && !process.env[k]) process.env[k] = rest.join('=').replace(/^["']|["']$/g, '')
}
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL })
const COMPANY_ID = 3

// ── Helpers ───────────────────────────────────────────────────────────────────
function cleanPhone(p) {
  if (!p) return null
  const d = p.replace(/\D/g, '')
  return d || null
}
function cleanInsta(v) {
  if (!v) return null
  if (v.includes('instagram.com/')) {
    const m = v.match(/instagram\.com\/([^/?#\s]+)/)
    return m ? m[1] : null
  }
  return v.replace(/^@/, '') || null
}
function nota(s) {
  if (!s) return null
  if (s === 'Fraco')     return 1
  if (s === 'Médio')     return 2
  if (s === 'Excelente') return 3
  return null
}

// ── Carrega status e sellers do banco ────────────────────────────────────────
const { rows: statusRows } = await pool.query(
  `SELECT id, nome FROM status WHERE company_id = $1`, [COMPANY_ID]
)
const statusMap = {}
for (const r of statusRows) statusMap[r.nome.toLowerCase()] = r.id

// Cria status que faltarem
async function getOrCreateStatus(nome) {
  if (statusMap[nome.toLowerCase()]) return statusMap[nome.toLowerCase()]
  const { rows } = await pool.query(
    `INSERT INTO status (nome, cor, ordem, company_id) VALUES ($1,'#6b7280',99,$2) RETURNING id`,
    [nome, COMPANY_ID]
  )
  statusMap[nome.toLowerCase()] = rows[0].id
  console.log(`  ✅ Status criado: "${nome}"`)
  return rows[0].id
}

const { rows: sellerRows } = await pool.query(
  `SELECT id, nome FROM sellers WHERE company_id = $1`, [COMPANY_ID]
)
const sellerMap = {}
for (const r of sellerRows) sellerMap[r.nome.toLowerCase()] = r.id

async function getOrCreateSeller(nome) {
  if (!nome) return null
  const k = nome.toLowerCase()
  if (sellerMap[k]) return sellerMap[k]
  const { rows } = await pool.query(
    `INSERT INTO sellers (nome, company_id) VALUES ($1,$2) ON CONFLICT DO NOTHING RETURNING id`,
    [nome, COMPANY_ID]
  )
  if (rows[0]) {
    sellerMap[k] = rows[0].id
    console.log(`  ✅ Seller criado: "${nome}"`)
    return rows[0].id
  }
  const { rows: ex } = await pool.query(`SELECT id FROM sellers WHERE LOWER(nome)=$1 AND company_id=$2`, [k, COMPANY_ID])
  sellerMap[k] = ex[0].id
  return ex[0].id
}

// ── Insert helper ─────────────────────────────────────────────────────────────
let inserted = 0, skipped = 0
async function ins(c) {
  const statusId = await getOrCreateStatus(c.status || 'Prospecção')
  const sellerId = await getOrCreateSeller(c.seller || null)
  const { rowCount } = await pool.query(
    `INSERT INTO clients (nome, cidade, uf, whatsapp, email, instagram, site, nota, status_id, seller_id, company_id, user_id)
     SELECT $1::varchar,$2::varchar,$3::varchar,$4::varchar,$5::varchar,$6::varchar,$7::varchar,$8::int,$9::int,$10::int,$11::int,
            (SELECT id FROM users WHERE company_id=$11::int ORDER BY id LIMIT 1)
     WHERE NOT EXISTS (
       SELECT 1 FROM clients WHERE LOWER(TRIM(nome))=LOWER($1::varchar) AND uf=$3::varchar AND company_id=$11::int
     )`,
    [
      c.nome, c.cidade || null, c.uf,
      cleanPhone(c.whatsapp), c.email || null,
      cleanInsta(c.instagram), c.site || null,
      nota(c.nota), statusId, sellerId, COMPANY_ID,
    ]
  )
  if (rowCount > 0) inserted++
  else skipped++
}

// ── Dados do PDF (31/03/2026) ─────────────────────────────────────────────────
console.log('\n▶ Inserindo clientes do PDF...')

const clientes = [
  // ── MS ───────────────────────────────────────────────────────────────────
  { nome:'Andrade Bicicletas',cidade:'Três Lagoas',uf:'MS',whatsapp:'67992991054',status:'Contatado',seller:'Thiago' },
  { nome:'Bicicletaria Cicles União',cidade:'Ponta Porã',uf:'MS',whatsapp:'67996883293',status:'Contatado',seller:'Thiago' },
  { nome:'Bicicletaria Garoto',cidade:'Três Lagoas',uf:'MS',whatsapp:'6799656834',instagram:'https://www.instagram.com/bikegaroto/',status:'Contatado',seller:'Thiago' },
  { nome:'Bicicletaria JF Pacheco',cidade:'Coxim',uf:'MS',whatsapp:'67996609380',email:'sandyfpacheco@hotmail.com',instagram:'https://www.instagram.com/bicicletaria_jf/',status:'Contatado',seller:'Thiago' },
  { nome:'Bicicletaria Santos',cidade:'Três Lagoas',uf:'MS',whatsapp:'6799282787',email:'bicicletariasantos@hotmail.com',instagram:'https://www.instagram.com/santosbicicletaria/',status:'Contatado',seller:'Thiago' },
  { nome:'Bicicletaria Santos (Revenda OGGI)',cidade:'Três Lagoas',uf:'MS',whatsapp:'6799282787',instagram:'https://www.instagram.com/santosbicicletaria/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Bike Adventure',cidade:'Naviraí',uf:'MS',whatsapp:'6799900100',instagram:'https://www.instagram.com/bikeadventureoficial/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Mart',cidade:'Campo Grande',uf:'MS',whatsapp:'6799284998',email:'daniel@bikemart.com.br',instagram:'https://www.instagram.com/bikemart.br/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Shop By Pró-bike',cidade:'Dourados',uf:'MS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike.com Comércio de Bicicletas',cidade:'Dourados',uf:'MS',whatsapp:'67998577306',instagram:'@Interior',status:'Contatado',seller:'Thiago' },
  { nome:'Bonito Eco Bike',cidade:'Bonito',uf:'MS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo Brasil',cidade:'Ponta Porã',uf:'MS',whatsapp:'67996515142',email:'ciclobrasil@hotmail.com',instagram:'https://www.instagram.com/ciclobrasil/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo Fernandes',cidade:'Dourados',uf:'MS',whatsapp:'6782224061',instagram:'https://www.instagram.com/ciclofernandes_dourados/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo Pixote',cidade:'Corumbá',uf:'MS',whatsapp:'6799161842',instagram:'https://www.instagram.com/ciclopixote/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo Reis (Revenda OGGI)',cidade:'Campo Grande',uf:'MS',whatsapp:'6773014347',instagram:'https://www.instagram.com/cicloreis/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo Reis Aquidauana',cidade:'Campo Grande',uf:'MS',whatsapp:'6799688482',instagram:'https://www.instagram.com/cicloreis.aquidauana/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo Reis Calógeras',cidade:'Campo Grande',uf:'MS',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo Reis Pioneiras',cidade:'Campo Grande',uf:'MS',whatsapp:'6799466291',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo_mar',cidade:'Campo Grande',uf:'MS',whatsapp:'6799277450',instagram:'https://www.instagram.com/ciclo_mar/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclocenter Bike Shop',cidade:'Dourados',uf:'MS',whatsapp:'67999095474',instagram:'https://www.instagram.com/ciclocenter_dourados/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclotoni',cidade:'Campo Grande',uf:'MS',whatsapp:'67992371396',email:'ciclotoni1@hotmail.com',instagram:'https://www.instagram.com/ciclotonims/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Concept Bike Shop',cidade:'Campo Grande',uf:'MS',email:'contato@conceptbikeshop.com.br',instagram:'https://www.instagram.com/conceptbikeshop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Conserta Bike Três Lagoas',cidade:'Três Lagoas',uf:'MS',whatsapp:'67998684923',email:'treslagoas@consertabike.com',instagram:'https://www.instagram.com/consertabike.treslagoas/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'ELIO BIKE SHOP',cidade:'Paranaíba',uf:'MS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'ELIO BIKESHOP LOJA 2',cidade:'Paranaíba',uf:'MS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Eletro Bike EBN',cidade:'Naviraí',uf:'MS',instagram:'https://www.instagram.com/eletr_obike/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Elite Motos e Negócios',cidade:'Ponta Porã',uf:'MS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'GMT Mobilidade Elétrica (Três Lagoas)',cidade:'Três Lagoas',uf:'MS',whatsapp:'67993119017',email:'contato@gambaratto.com.br',instagram:'https://www.instagram.com/gmtmobilidade.treslagoas/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Gambaratto Dourados',cidade:'Dourados',uf:'MS',whatsapp:'67993403995',email:'contato@gambaratto.com.br',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Gilbike Motos e Acessórios',cidade:'Sidrolândia',uf:'MS',whatsapp:'67999173655',email:'gilbikemotosacessorios@gmail.com',instagram:'https://www.instagram.com/gilbikemotos/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Gilmar Bicicletas',cidade:'Campo Grande',uf:'MS',whatsapp:'6733841118',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Greffe Bike',cidade:'Campo Grande',uf:'MS',whatsapp:'67992437368',instagram:'https://www.instagram.com/greffebikeeletrica/',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'HS Bicicletaria',cidade:'Ponta Porã',uf:'MS',whatsapp:'6798454217',email:'hs.bicicletaria.1994@gmail.com',instagram:'https://www.instagram.com/hs.bicicletaria/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Hélio Bikes',cidade:'Dourados',uf:'MS',whatsapp:'67991490977',instagram:'https://www.instagram.com/helio.bikes/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ideia Bikes Elétricas',cidade:'Nova Andradina',uf:'MS',instagram:'https://www.instagram.com/ideiabikeseletricas/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Idéia bicicleta e motos',cidade:'Nova Andradina',uf:'MS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'JJ Motos e JJ Bikes',cidade:'Nova Andradina',uf:'MS',email:'jjmotos@bol.com',instagram:'https://www.instagram.com/jjmotosebike/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Juliano Bikes',cidade:'Paranaíba',uf:'MS',whatsapp:'6798138866',instagram:'https://www.instagram.com/julianobikespba/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Km Bikes & Motos',cidade:'Santana do Paranaíba',uf:'MS',email:'contato@2wmotors.com.br',instagram:'https://www.instagram.com/kmbikes/',status:'Contatado',seller:'Thiago' },
  { nome:'Livre Bikes',cidade:'Três Lagoas',uf:'MS',whatsapp:'6773521908',email:'orientehelena@gmail.com',instagram:'https://www.instagram.com/livrebikes/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Luan Bike',cidade:'Campo Grande',uf:'MS',instagram:'https://www.instagram.com/luanbikeof_/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Lucas Bike',cidade:'Campo Grande',uf:'MS',instagram:'https://www.instagram.com/lucas_bike_1/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Mechanics Motos',cidade:'Ponta Porã',uf:'MS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Moove Bikes Elétricas',cidade:'Corumbá',uf:'MS',whatsapp:'67998335080',instagram:'https://www.instagram.com/moovepantanal/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Moto Elétricas J&B Multimarcas',cidade:'Três Lagoas',uf:'MS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Nova R4+ Bicicletas',cidade:'Sidrolândia',uf:'MS',whatsapp:'6799112948',instagram:'https://www.instagram.com/r4bicicletasoficial/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Novar4+ bicicletas',cidade:'Sidrolândia',uf:'MS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'PIU BIKE Bicicletaria',cidade:'Naviraí',uf:'MS',whatsapp:'67998358845',email:'piu_bike@hotmail.com',instagram:'https://www.instagram.com/bicicletaria_piubike/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'PRÓ-BIKE Casa das Bicicletas',cidade:'Dourados',uf:'MS',whatsapp:'67996409721',instagram:'https://www.instagram.com/probikeddos/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Pedal Elétrico - Locações e Serviços',cidade:'Bonito',uf:'MS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Pedal de Ouro',cidade:'Paranaíba',uf:'MS',instagram:'https://www.instagram.com/pedaldeouro_bikes/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Piabas Bike Shop',cidade:'Corumbá',uf:'MS',whatsapp:'67998834110',instagram:'https://www.instagram.com/piabasbikeshop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Prime Bikes & Motos',cidade:'Naviraí',uf:'MS',email:'dheprimiani@gmail.com',instagram:'https://www.instagram.com/primebikesemotos/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Pró Bike Casa das Bicicletas (Revenda OGGI)',cidade:'Dourados',uf:'MS',whatsapp:'67981805833',status:'Contatado',seller:'Thiago' },
  { nome:'R J Bike Bicicletaria Nova Andradina',cidade:'Nova Andradina',uf:'MS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Santana Bike Shop',cidade:'Campo Grande',uf:'MS',whatsapp:'556730268643',instagram:'https://www.instagram.com/santanabikeshopms/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Smart Bike Shop',cidade:'Campo Grande',uf:'MS',instagram:'https://www.instagram.com/smartbikeshop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Super Bike',cidade:'Aquidauana',uf:'MS',whatsapp:'6773241839',instagram:'https://www.instagram.com/super_bike_shop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'São Paulo Moto Bike e Peças',cidade:'Coxim',uf:'MS',whatsapp:'6799647371',instagram:'https://www.instagram.com/saopaulomoto/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Tamanduá Bike Store',cidade:'Campo Grande',uf:'MS',whatsapp:'67998155640',instagram:'https://www.instagram.com/tamanduabike/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'TotalBike Bicicletaria',cidade:'Aquidauana',uf:'MS',instagram:'https://www.instagram.com/totalbike_aquidauana/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Turbo Bike Elétrica',cidade:'Coxim',uf:'MS',whatsapp:'67996859774',instagram:'https://www.instagram.com/turbo_bikee/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Universo Bikes e Motos',cidade:'Naviraí',uf:'MS',whatsapp:'67984725067',email:'novauniverso1@gmail.com',instagram:'https://www.instagram.com/universobikesemotos/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'arcanjosbikeshop',cidade:'Campo Grande',uf:'MS',whatsapp:'67992869245',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'bikeeletricasaad',cidade:'Campo Grande',uf:'MS',whatsapp:'6799177592',email:'bikeeletricasaad@gmail.com',instagram:'https://www.instagram.com/bikeeletricasaad/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'gino_bikesz0',cidade:'Campo Grande',uf:'MS',whatsapp:'6792901038',instagram:'https://www.instagram.com/ginobikes/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'iuri.wb',cidade:'Campo Grande',uf:'MS',whatsapp:'6791855440',instagram:'https://www.instagram.com/iuri.wb/reels/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  // ── MT ───────────────────────────────────────────────────────────────────
  { nome:'3rd Coast Cycles Bicycle',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Adrenalina Esporte Bike',cidade:'Cuiabá',uf:'MT',whatsapp:'65996601293',email:'adrenalinaesportebikes01@gmail.com',instagram:'adrenalinacba',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'Art Bikes Jax',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'BOLT • Elétricos',cidade:'Cuiabá',uf:'MT',whatsapp:'6599278543',instagram:'https://www.instagram.com/bolteletricos/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'BRASIL BIKE',cidade:'Lucas do Rio Verde',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'BYKE Collective',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Baltimore Bicycle Works',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bat-Bike USA',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Baynesville Bicycle Shop',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Beto Bicicletas',cidade:'Barra do Garças',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Cross',cidade:'Primavera do Leste',uf:'MT',instagram:'bicicletariacross',status:'Prospecção',seller:'Thiago' },
  { nome:"Bicicletaria Ninu's Bike - Sorriso-MT",cidade:'Sorriso',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Sinop',cidade:'Sinop',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria moraes',cidade:'Lucas do Rio Verde',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicycle Clinic Llc',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicycle Connection',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicycles Etc.',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Big Bikes Tga',cidade:'Tangará da Serra',uf:'MT',whatsapp:'6599610122',email:'marcelocrestani@hotmail.com',instagram:'https://www.instagram.com/bigbikes.tga/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike 25 Outlet Cuiabá',cidade:'Cuiabá',uf:'MT',whatsapp:'6599256622',instagram:'https://www.instagram.com/bike25cuiaba/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Bike Center',cidade:'Tangará da Serra',uf:'MT',email:'bikecentertga@outlook.com',instagram:'https://www.instagram.com/bike_center_tangara/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Clinic',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Mania',cidade:'Tangará da Serra',uf:'MT',instagram:'https://www.instagram.com/bikemaniatga/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Masters',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Motos - São Cristovão - Sinop - mt',cidade:'Sinop',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Ride Sobe',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Show - Buriti',cidade:'Rondonópolis',uf:'MT',whatsapp:'6673425396',instagram:'https://www.instagram.com/bikeshowb/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike&Bike',cidade:'Juína',uf:'MT',email:'bikejuina@gmail.com',instagram:'https://www.instagram.com/bikebike_juina/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:"Bike's Mato Grosso",cidade:'Cáceres',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bobby\'s Bike Hike',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Brickell Bikes',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bueno Bike Shop',cidade:'Cuiabá',uf:'MT',whatsapp:'6599224044',instagram:'https://www.instagram.com/buenobikeshopp/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Bullseye Bicycle',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bustleton Bikes',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'CK Bikes',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Casa Das Bikes',cidade:'Cáceres',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Casa das Bicicletas',cidade:'Sorriso',uf:'MT',whatsapp:'66984478240',instagram:'https://www.instagram.com/casadasbicicletassorriso/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Catonsville Bicycles and Skateboards',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Central Motos e Bikes',cidade:'Sorriso',uf:'MT',instagram:'centralmotosebikessorriso',status:'Prospecção',seller:'Thiago' },
  { nome:'Ciclo 1',cidade:'Sinop',uf:'MT',instagram:'ciclo1sinop',status:'Prospecção',seller:'Thiago' },
  { nome:'Ciclo Brasil Motos Bicicletas',cidade:'Várzea Grande',uf:'MT',whatsapp:'65992070723',instagram:'ciclobrasilmb',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'Ciclo Center Sorriso',cidade:'Sorriso',uf:'MT',instagram:'https://www.instagram.com/ciclocentersorriso/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo Machado Cuiabá',cidade:'Cuiabá',uf:'MT',whatsapp:'6599600511',instagram:'https://www.instagram.com/ciclomachado_cba/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo Machado VG',cidade:'Várzea Grande',uf:'MT',whatsapp:'6599265395',instagram:'https://www.instagram.com/ciclomachadomt/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo Motos E Bicicletas',cidade:'Várzea Grande',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo Rabelo',cidade:'Várzea Grande',uf:'MT',whatsapp:'6599208054',email:'ciclorabelovg@hotmail.com',instagram:'Ciclorabelo',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo Sport Bicicletas',cidade:'Rondonópolis',uf:'MT',whatsapp:'66999965343',status:'Contatado',seller:'Thiago' },
  { nome:'Ciclo Urbano Bike Shop',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo1 Sinop',cidade:'Sinop',uf:'MT',whatsapp:'66999433930',instagram:'https://www.instagram.com/ciclo1sinop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'City Bikes Midtown',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Conserta Bike Sinop',cidade:'Sinop',uf:'MT',whatsapp:'6699213805',email:'sinop@consertabike.com',instagram:'https://www.instagram.com/consertabike_sinop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Cross Bike',cidade:'Cáceres',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Cuiabá Bicicletas',cidade:'Cuiabá',uf:'MT',whatsapp:'65999008630',instagram:'https://www.instagram.com/cuiababicicletas/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Cycle Tech, Inc.',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Dirt Rooster Bicycles',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Dual Bike',cidade:'Sinop',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'ELECTRIC LANE',uf:'MT',instagram:'electriclanechicago',status:'Prospecção',seller:'Thiago' },
  { nome:'ELECTRO BIKE',cidade:'Lucas do Rio Verde',uf:'MT',instagram:'electro_bike_lrv',status:'Prospecção',seller:'Thiago' },
  { nome:'El eBike Doc y Mas',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Electric Movement',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Eletro Bikes Sinop',cidade:'Sinop',uf:'MT',whatsapp:'66996168686',instagram:'https://www.instagram.com/eletro.bikes.sinop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Eletro Racing Scooters Elétricas',cidade:'Cuiabá',uf:'MT',whatsapp:'65996262059',email:'contato.eletroracing@gmail.com',instagram:'https://www.instagram.com/eletroracing/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Elite Bike Store',cidade:'Sinop',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Esportiva Bikes',cidade:'Primavera do Leste',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Estrela Sport Bike',cidade:'Tangará da Serra',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:"Flythe's Bike Shop",uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'GR Bicicletas',cidade:'Várzea Grande',uf:'MT',instagram:'https://www.instagram.com/gr.bicicletas/',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'Giraia Bike Shop',cidade:'Sorriso',uf:'MT',instagram:'https://www.instagram.com/giraia_bike_shop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Hobby Bikers (Revenda OGGI)',cidade:'Cuiabá',uf:'MT',whatsapp:'66999083996',instagram:'https://www.instagram.com/hobbybikerscba/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'J\'s Bikes',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'JAVIS BIKE SHOP',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:"Joe's Bike Shop",uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'LE BIKE',cidade:'Tangará da Serra',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'La Bendicion Bicycle',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Lake Cycle',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Mega Scooter Cuiabá',cidade:'Cuiabá',uf:'MT',whatsapp:'65998097646',status:'Contatado',seller:'Thiago' },
  { nome:'Miami Beach Bicycle Center',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Miami Bikes Electric Bicycle Shop',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Miami Bikes and Repair',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Miami Cycles',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Mova Scooter',cidade:'Juína',uf:'MT',whatsapp:'66996748884',instagram:'@Interior',status:'Contatado',seller:'Thiago' },
  { nome:'Mr Bikes Rental & Scooters',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Ninus Bike Alta Floresta',cidade:'Alta Floresta',uf:'MT',instagram:'https://www.instagram.com/ninusbike/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Open Road Bicycles',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'PAPERtrail Bike Cafe',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Peak Bicycle and Ski Service',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Pedal To The People',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Pedalando Bike Shop',cidade:'Lucas do Rio Verde',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Pikesville Bicycle Shop',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Plugin Eletromobilidade - Primavera',cidade:'Primavera do Leste',uf:'MT',instagram:'plugineletromobilidade',status:'Prospecção',seller:'Thiago' },
  { nome:'Pva Bike',cidade:'Primavera do Leste',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'R Bike Shop MT',cidade:'Várzea Grande',uf:'MT',whatsapp:'65993294549',instagram:'rbikeshopmt',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'REI DAS BIKES',cidade:'Lucas do Rio Verde',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Radical Bike Cuiabá',cidade:'Cuiabá',uf:'MT',instagram:'https://www.instagram.com/radicalbikecuiaba/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ruedas Miami Rental Repair',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'S2 Bike Shop Cuiabá',cidade:'Cuiabá',uf:'MT',whatsapp:'6573649317',instagram:'https://www.instagram.com/s2cuiabamt/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'S2 Bike Shop Rondonópolis',cidade:'Rondonópolis',uf:'MT',whatsapp:'66996868121',instagram:'s2rondonopolismt',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'SLS Electric Motors',cidade:'Primavera do Leste',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'SOMI BIKE',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:"SPEED BIKE'S bicicletaria em cáceres",cidade:'Cáceres',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Sanchez Bike Repair',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Scooter Repair',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Secreta Bike',cidade:'Barra do Garças',uf:'MT',instagram:'https://www.instagram.com/secretabike/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Sorribike bicicletaria',cidade:'Sorriso',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'SunCycling Cycle and Fitness Shop',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Tienda motos eléctricas',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Trek Bicycle Towson',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Trial Bikes',cidade:'Sinop',uf:'MT',whatsapp:'66999992238',status:'Contatado',seller:'Thiago' },
  { nome:'UaU Bikes',cidade:'Barra do Garças',uf:'MT',email:'uaubikesbg@gmail.com',instagram:'https://www.instagram.com/uaubikes/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Val bike',cidade:'Várzea Grande',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Velocipede Bike Project',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Vertys Motors Tangará',cidade:'Tangará da Serra',uf:'MT',instagram:'https://www.instagram.com/vertys_motorstangara/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Villa Motor Sports',cidade:'Cuiabá',uf:'MT',whatsapp:'65996496262',status:'Contatado',seller:'Thiago' },
  { nome:'Watts Rondonópolis',cidade:'Rondonópolis',uf:'MT',whatsapp:'66999678467',status:'Contatado',seller:'Thiago' },
  { nome:'West Town Bikes',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'ZenCog Bicycle Company',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'eBikeling',uf:'MT',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  // ── PE ───────────────────────────────────────────────────────────────────
  { nome:'Fast Scooter - Bikes elétricas, scooter elétrica e patinetes',cidade:'Recife',uf:'PE',status:'Prospecção',nota:'Fraco',seller:'Daniela' },
  // ── PR ───────────────────────────────────────────────────────────────────
  { nome:'A Bicicletaria',cidade:'Curitiba',uf:'PR',instagram:'abicicletaria',status:'Contatado',seller:'Thiago' },
  { nome:'AMJ Bike Shop',cidade:'Sarandi',uf:'PR',instagram:'https://www.instagram.com/amj.bikeshop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Agencia Bicicleta',cidade:'Curitiba',uf:'PR',whatsapp:'41988055971',email:'alexandre@agenciabicicleta.com.br',instagram:'https://www.instagram.com/agencia_bicicleta/',status:'Fabricação Própria',nota:'Fraco',seller:'Thiago' },
  { nome:'Alex Ribeiro Sports',cidade:'Curitiba',uf:'PR',whatsapp:'41992676838',instagram:'alexribeiro.sports',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Alpha Bikes',cidade:'Palotina',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Alugar bike em Matinhos e Caiobá',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Amaral Bikes Paranaguá',cidade:'Paranaguá',uf:'PR',whatsapp:'41996482151',instagram:'amaralbikesparanagua',status:'Contatado',seller:'Thiago' },
  { nome:'Américo Bikes',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Ana Bike | Bicicletaria',cidade:'Apucarana',uf:'PR',instagram:'https://www.instagram.com/anabikee/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:"Andrad's bike",cidade:'Guaratuba',uf:'PR',instagram:'andradsbike_oficial',status:'Prospecção',seller:'Thiago' },
  { nome:'Arena Motos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Armazém Moto Peças',cidade:'Paranaguá',uf:'PR',whatsapp:'4173427265',instagram:'armazemmotopecas',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Aro 29',cidade:'Campo Mourão',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Atomi Teste',uf:'PR',whatsapp:'11923165330',email:'thiago.nivelatomi@gmail.com',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'BICICLETAETRICICLOELETRICO',cidade:'Palotina',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'BIKE PRONTA Loja & Oficina - Campo Mourão',cidade:'Campo Mourão',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'BIKE TECH',cidade:'Curitiba',uf:'PR',whatsapp:'4184186269',status:'Fabricação Própria',seller:'Thiago' },
  { nome:'BIKE4U',cidade:'Curitiba',uf:'PR',whatsapp:'41992442444',instagram:'Bikeparavoce',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'BK BIKES - BICICLETAS, PEÇAS E ACESSÓRIOS',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'BL Bikes - Atacado e Varejo',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Baron Bikes',cidade:'Curitiba',uf:'PR',instagram:'https://www.instagram.com/baronbikes/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Baterias ForteX',cidade:'Maringá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bayer Bike',cidade:'Toledo',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bici Bikes Cabral',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicleta Elétrica Veloster',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Altair Cycles',cidade:'Foz do Iguaçu',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Avenida',cidade:'Toledo',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Bem te Vi',cidade:'Guaratuba',uf:'PR',whatsapp:'41998098424',instagram:'bicicletaria.bem.te.vi',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Bem-Te-Vi',cidade:'Guaratuba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Beto bikes',cidade:'Guaratuba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Cultural',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Ipanema',cidade:'Pontal do Paraná',uf:'PR',instagram:'bicicletariaipanema',status:'Contatado',seller:'Thiago' },
  { nome:'Bicicletaria J. bikes Carambei',cidade:'Carambeí',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Lira & Costa',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria MaréxBikes',cidade:'Guaratuba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria ND Bikes Matinhos Pr',cidade:'Matinhos',uf:'PR',instagram:'nd_bikes',status:'Prospecção',seller:'Thiago' },
  { nome:'Bicicletaria Oeste',cidade:'Palotina',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Silvera',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Sport',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria TOPA TUDO',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria do Catarina',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria do Fride',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria e Borracharia Silva',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Biciclo Comércio de Bicicletas Peças e Acessórios',cidade:'Guaratuba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Big Bike Mobilidade',cidade:'Ponta Grossa',uf:'PR',whatsapp:'4273025186',instagram:'https://www.instagram.com/bigbikepg/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Bike Batel',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Brothers',cidade:'Curitiba',uf:'PR',whatsapp:'41988446807',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Center Elétricas',cidade:'Sarandi',uf:'PR',whatsapp:'44997748712',instagram:'@Interior',status:'Contatado',seller:'Thiago' },
  { nome:'Bike Doctor',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike G3',cidade:'Francisco Beltrão',uf:'PR',whatsapp:'46988031600',instagram:'https://www.instagram.com/bikeg3fb/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Melhor Preço',cidade:'Maringá',uf:'PR',instagram:'bikemelhorpreco',status:'Prospecção',seller:'Thiago' },
  { nome:'Bike Portella',cidade:'Curitiba',uf:'PR',whatsapp:'41732623707',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Power',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Service',cidade:'Curitiba',uf:'PR',whatsapp:'4173408951',instagram:'https://www.instagram.com/bikeservicectba/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Shop - Adventure',cidade:'São José dos Pinhais',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Strong',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Sul',cidade:'Guaratuba',uf:'PR',whatsapp:'41991548404',instagram:'bikesulguaratuba',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Trip',cidade:'Curitiba',uf:'PR',whatsapp:'41730761816',instagram:'https://www.instagram.com/biketripbr/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike51 - Bicicletas, Acessórios e muito mais',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'BikeTech Paranaguá',cidade:'Paranaguá',uf:'PR',whatsapp:'41995311022',instagram:'biketechpgua',status:'Contatado',seller:'Thiago' },
  { nome:'Bikesport',cidade:'Curitiba',uf:'PR',instagram:'https://www.instagram.com/bikesport_cwb/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Biks Store',cidade:'Guarapuava',uf:'PR',email:'suicidebmx@hotmail.com',instagram:'https://www.instagram.com/biksstore/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Black Bike',cidade:'Guaratuba',uf:'PR',whatsapp:'41985173773',instagram:'black_bikegtba',status:'Contatado',seller:'Thiago' },
  { nome:'Bornancin Motos',cidade:'Paranaguá',uf:'PR',whatsapp:'41984825625',instagram:'bornancinmotos',status:'Contatado',seller:'Thiago' },
  { nome:'Box313',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bravo Bikes Ponta Grossa',cidade:'Ponta Grossa',uf:'PR',whatsapp:'4284026236',instagram:'https://www.instagram.com/bravobikespg/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Brio Electric Toledo',cidade:'Toledo',uf:'PR',instagram:'brio_electric',status:'Prospecção',seller:'Thiago' },
  { nome:'Brychtabikes',cidade:'Curitiba',uf:'PR',whatsapp:'41995531622',instagram:'https://www.instagram.com/brychtabikes/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Buguelo Bikes',cidade:'Dois Vizinhos',uf:'PR',whatsapp:'46999036974',instagram:'@Interior',status:'Contatado',seller:'Thiago' },
  { nome:'By Box31 oficina de moto',cidade:'Guaratuba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'CASTRO Bike',cidade:'Castro',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'CBS Curitiba Bike Store',cidade:'Curitiba',uf:'PR',whatsapp:'41991984155',instagram:'https://www.instagram.com/curitibabikestore/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'CICLES ANDRADE',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'CICLES ROQUE BICICLETAS',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'CONSERT CICLOMOTORES',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'CYKLOS Londrina',cidade:'Londrina',uf:'PR',whatsapp:'4399166991',instagram:'https://www.instagram.com/cyklos.londrina/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Caioba bike',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Cantelli Bike Shop',cidade:'Curitiba',uf:'PR',whatsapp:'4688228385',instagram:'https://www.instagram.com/cantelli.bikeshop/',status:'Contatado',seller:'Thiago' },
  { nome:'Carlinhos Motos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Carlos Motos e Bikes Elétricas',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Casa da Moto - Peças e Acessórios',cidade:'Morretes',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Central Bike',cidade:'Ibiporã',uf:'PR',whatsapp:'4373258485',instagram:'https://www.instagram.com/storecentralbike/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Cicles Contorno',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Cicles Gabriel',cidade:'Curitiba',uf:'PR',whatsapp:'5541998610206',instagram:'https://www.instagram.com/cicles_gabriel/',status:'Contatado',seller:'Thiago' },
  { nome:'Cicles Jaime',cidade:'Curitiba',uf:'PR',whatsapp:'4179723040',instagram:'https://www.instagram.com/ciclesjaime/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Cicles Langner',cidade:'Curitiba',uf:'PR',whatsapp:'5541987970865',instagram:'https://www.instagram.com/cicles_langner/',status:'Contatado',seller:'Thiago' },
  { nome:'Cicles Ninja',cidade:'Paranaguá',uf:'PR',instagram:'ciclesninja',status:'Prospecção',seller:'Thiago' },
  { nome:'Cicles Roque Bike',cidade:'Matinhos',uf:'PR',whatsapp:'41997385747',instagram:'cicles_roque_bike',status:'Contatado',seller:'Thiago' },
  { nome:'Ciclescentral',cidade:'Curitiba',uf:'PR',whatsapp:'41992076721',instagram:'https://www.instagram.com/ciclescentral_/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclesradar',cidade:'Curitiba',uf:'PR',whatsapp:'5541998228665',email:'ciclesradar@hotmail.com',instagram:'https://www.instagram.com/ciclesradar/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Ciclo Santos Bicicletaria',cidade:'Morretes',uf:'PR',whatsapp:'4173462143',email:'ciclosantosmts@hotmail.com',instagram:'ciclosantosbicicletaria',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'CicloBell Bikes',cidade:'Guaratuba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Conserta Bike Matinhos',cidade:'Matinhos',uf:'PR',instagram:'consertabikematinhos',status:'Prospecção',seller:'Thiago' },
  { nome:'Conserta Bike Portão',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'ConsertaBike Maringá',cidade:'Maringá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Costa Azul bikes e motos',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Cr Bikes',cidade:'Curitiba',uf:'PR',whatsapp:'4179567240',email:'contato@crbikes.com.br',instagram:'https://www.instagram.com/cr_bikes_/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Curitiba Bike Store',cidade:'Curitiba',uf:'PR',whatsapp:'41991984155',instagram:'https://www.instagram.com/curitibabikestore/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Cycle Therapy',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:"D'anas Bike",cidade:'Francisco Beltrão',uf:'PR',whatsapp:'4673030554909',instagram:'https://www.instagram.com/danas_bike/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Demer Motors Paranaguá',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Dias Bike Maringá',cidade:'Maringá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Dias Bike Toledo',cidade:'Toledo',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Dias Bike e Moto',cidade:'Cianorte',uf:'PR',whatsapp:'4499940596',instagram:'https://www.instagram.com/diasbikecia/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Donizete Moto | locação de motos',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Duas Rodas Bike Shop',cidade:'Dois Vizinhos',uf:'PR',whatsapp:'46992292299',instagram:'@Interior',status:'Contatado',seller:'Thiago' },
  { nome:'E-Bike Brasil',cidade:'Foz do Iguaçu',uf:'PR',instagram:'ebikebrasilfoz',status:'Prospecção',seller:'Thiago' },
  { nome:'E-Bike CWB',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'EDM BIKE MOTOS',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'EcoDrive Mobilidade',cidade:'Curitiba',uf:'PR',whatsapp:'5541995495157',email:'contato@ecodrive.com.br',instagram:'https://www.instagram.com/ecodrive_curitiba/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Eletro1000 Maringá',cidade:'Maringá',uf:'PR',whatsapp:'4443200020',instagram:'https://www.instagram.com/eletro_1000_maringa/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'EletroBike - Bicicletas Elétricas',cidade:'Maringá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Elithe Motoshop',cidade:'Curitiba',uf:'PR',whatsapp:'41991411714',instagram:'https://www.instagram.com/elithemotoseletricas/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Elvis Moto Peças',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Elétric House',cidade:'Cascavel',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Elétrica Mobile',cidade:'Cascavel',uf:'PR',whatsapp:'45999559687',email:'eletricamobile@gmail.com',instagram:'https://www.instagram.com/eletricamobile/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Extreme Bikes',cidade:'Curitiba',uf:'PR',email:'osniextreme@gmail.com',instagram:'https://www.instagram.com/extremebikescuritiba/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'FS Bicicletas Elétrica - Maringá',cidade:'Maringá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Farias Bike Shop',cidade:'Paranavaí',uf:'PR',instagram:'https://www.instagram.com/farias_bike_pvai/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Feijão Motos Oficina',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Ferracioli Bike Shop',cidade:'Apucarana',uf:'PR',email:'ferraciolibikeshop@gmail.com',instagram:'https://www.instagram.com/ferraciolibikeshop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Fiets',cidade:'São José dos Pinhais',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Flaviano Bikes e Motos',cidade:'Paranaguá',uf:'PR',whatsapp:'41985366467',instagram:'flavianobikesemotos',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Foz Bike Bicicletaria',cidade:'Foz do Iguaçu',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Fsbicicletas',cidade:'Maringá',uf:'PR',whatsapp:'44999514563',instagram:'https://www.instagram.com/fsbicicletas/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:"G'IBÓIAS BIKES",cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'GORDINHO MOTOS',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'GT Bike Shop',cidade:'Arapongas',uf:'PR',whatsapp:'43999653047',instagram:'https://www.instagram.com/gt_bikeshop_/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Garage Bike Parts',cidade:'Guaratuba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Garagem dos Elétricos',cidade:'Toledo',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Gomes bike',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Guaratuba Bikes',cidade:'Guaratuba',uf:'PR',whatsapp:'41991720842',instagram:'guaratubabikes',status:'Contatado',seller:'Thiago' },
  { nome:'Guará Motor Oil',cidade:'Guaratuba',uf:'PR',instagram:'guaramotoroil',status:'Prospecção',seller:'Thiago' },
  { nome:'H-Bike Brasil',cidade:'Pinhais',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Honda Ecosul Matinhos',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Honda Ecosul Paranaguá',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Hunger Bikes',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'IMPULSO Eletric Motors - Paranaguá',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Israel Motos',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'I MOV Mobilidade Elétrica',cidade:'Curitiba',uf:'PR',whatsapp:'4188248004',instagram:'https://www.instagram.com/imovcuritiba/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'LC Bikes',cidade:'Guaratuba',uf:'PR',instagram:'_lcbikes',status:'Contatado',seller:'Thiago' },
  { nome:'LM Bike',cidade:'Morretes',uf:'PR',whatsapp:'41991254357',instagram:'lm.bicicletaria.acessorios',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Litoral Bike',cidade:'Matinhos',uf:'PR',whatsapp:'41997512138',instagram:'litoralbike.matinhos',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Loja das Bicicletas',cidade:'Apucarana',uf:'PR',whatsapp:'4373432122',email:'apucarana@lojadasbicicletas.com',instagram:'https://www.instagram.com/ldbapucarana/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'MOHELETRIC LTDA',cidade:'Castro',uf:'PR',instagram:'moheletric',status:'Prospecção',seller:'Thiago' },
  { nome:'MOW BIKES Curitiba',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Marander Bikes',cidade:'Matinhos',uf:'PR',instagram:'maranderbikes',status:'Contatado',seller:'Thiago' },
  { nome:'Marcell Veículos Elétricos',cidade:'Campo Mourão',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Marcelo motos',uf:'PR',instagram:'marcelomotosoficina',status:'Prospecção',seller:'Thiago' },
  { nome:'Marcos Reforma',cidade:'Palotina',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Marechal Bike',cidade:'Curitiba',uf:'PR',whatsapp:'41988427616',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Mariano Motos',cidade:'Paranaguá',uf:'PR',instagram:'marianomotosmariano',status:'Contatado',seller:'Thiago' },
  { nome:'Martins Bikes Paranaguá',cidade:'Paranaguá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Master Motos',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Mazi Bike Motos',cidade:'Campo Mourão',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Mega Elétron',cidade:'Curitiba',uf:'PR',instagram:'https://www.instagram.com/megaeletroncuritiba/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Mobilet Brasil',cidade:'Ponta Grossa',uf:'PR',whatsapp:'42988690699',instagram:'https://www.instagram.com/mobilets_brasil/',status:'Fabricação Própria',seller:'Thiago' },
  { nome:'Moto Bike',cidade:'Pato Branco',uf:'PR',email:'motobikeltda@gmail.com',instagram:'https://www.instagram.com/motobikemb/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'MotoChefe Maringá',cidade:'Maringá',uf:'PR',whatsapp:'44988381000',status:'Fabricação Própria',seller:'Thiago' },
  { nome:'Müller Bikes Curitiba',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'NXT Curitiba',cidade:'Curitiba',uf:'PR',whatsapp:'554196309513',status:'Contatado',seller:'Thiago' },
  { nome:'Na Pista 2 Rodas (Revenda OGGI)',cidade:'Maringá',uf:'PR',whatsapp:'43991569911',status:'Contatado',seller:'Thiago' },
  { nome:'Nova Bike Shop',cidade:'Matinhos',uf:'PR',whatsapp:'41996665869',instagram:'caiobabike',status:'Contatado',seller:'Thiago' },
  { nome:'PC Adventure',cidade:'Campo Mourão',uf:'PR',instagram:'pc.adventurebike',status:'Prospecção',seller:'Thiago' },
  { nome:'PC Motos',cidade:'Campo Mourão',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'POP Mobilidade Elétrica',cidade:'Curitiba',uf:'PR',whatsapp:'41992928800',status:'Contatado',seller:'Thiago' },
  { nome:'Pardalbikes',cidade:'Curitiba',uf:'PR',whatsapp:'5541997389245',status:'Contatado',seller:'Thiago' },
  { nome:'Patinep Store',cidade:'Maringá',uf:'PR',whatsapp:'44991110546',status:'Contatado',seller:'Thiago' },
  { nome:'Pato Bike',cidade:'Pato Branco',uf:'PR',whatsapp:'4688211146',instagram:'https://www.instagram.com/patobikepb/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Paulista Bikes',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Pedal Bike',cidade:'Francisco Beltrão',uf:'PR',whatsapp:'46999129440',email:'bicicletariapedalbike@outlook.com',instagram:'https://www.instagram.com/pedalbikefb/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Pedal de Ouro Bike Shop',cidade:'Cianorte',uf:'PR',whatsapp:'44997366312',instagram:'https://www.instagram.com/pedal_de_ouro_bikes/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Ponto das Bicicletas',cidade:'Ibiporã',uf:'PR',instagram:'https://www.instagram.com/pontodasbicicletas/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Pro Bikes Arapongas',cidade:'Arapongas',uf:'PR',whatsapp:'4373152514',status:'Contatado',seller:'Thiago' },
  { nome:'RAL Bike',cidade:'Cianorte',uf:'PR',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'RN Motoss',cidade:'Antonina',uf:'PR',whatsapp:'41987985609',instagram:'rnmotoss',status:'Contatado',seller:'Thiago' },
  { nome:'Rover Mobilidade Elétrica',cidade:'Curitiba',uf:'PR',whatsapp:'41730294163',status:'Fabricação Própria',seller:'Thiago' },
  { nome:'S2 Bike Shop Maringá',cidade:'Maringá',uf:'PR',whatsapp:'44998209067',status:'Contatado',seller:'Thiago' },
  { nome:'Scooter Club Maringá',cidade:'Maringá',uf:'PR',whatsapp:'4488191264',instagram:'https://www.instagram.com/scootercluboficial/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Scooter Londrina',cidade:'Londrina',uf:'PR',whatsapp:'43991303737',instagram:'scooterlondrinapr',status:'Fabricação Própria',nota:'Fraco',seller:'Thiago' },
  { nome:'Shazan Bike e Motos',cidade:'Arapongas',uf:'PR',whatsapp:'43999640507',status:'Contatado',seller:'Thiago' },
  { nome:'Star Watts',cidade:'Curitiba',uf:'PR',whatsapp:'41730182860',instagram:'https://www.instagram.com/wattscuritiba',status:'Contatado',seller:'Thiago' },
  { nome:'Tatu\'s Bike Shop',cidade:'Paranavaí',uf:'PR',whatsapp:'44999071226',instagram:'https://www.instagram.com/tatusbikeshop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Temotos',cidade:'Paranaguá',uf:'PR',whatsapp:'41996239674',instagram:'lojatemotos',status:'Contatado',seller:'Thiago' },
  { nome:'Torino Bikes',cidade:'Pato Branco',uf:'PR',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Total Ciclo',cidade:'Paranaguá',uf:'PR',instagram:'totalciclo',status:'Contatado',seller:'Thiago' },
  { nome:'Transbike',cidade:'Curitiba',uf:'PR',whatsapp:'41992650144',instagram:'https://www.instagram.com/transbikecuritiba/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Tropical bike',cidade:'Matinhos',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Two Dogs',cidade:'Curitiba',uf:'PR',whatsapp:'41992900337',instagram:'https://www.instagram.com/twodogs/',status:'Fabricação Própria',nota:'Médio',seller:'Thiago' },
  { nome:'URBE BICICLETAS ELETRICAS',cidade:'Maringá',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Urbanus Mobilidade Elétrica',cidade:'Ponta Grossa',uf:'PR',whatsapp:'42988385532',email:'urbanusmobilidade@gmail.com',instagram:'https://www.instagram.com/urbanus.mob/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Via Expressa Sports',cidade:'Cascavel',uf:'PR',instagram:'viaexpressasports',status:'Prospecção',seller:'Thiago' },
  { nome:'Voltage Bikes - Ciclismo e Mobilidade Elétrica',cidade:'Curitiba',uf:'PR',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Vou de Bike',cidade:'Guaratuba',uf:'PR',instagram:'voudebikegtba',status:'Contatado',seller:'Thiago' },
  { nome:'W Sport Bike',cidade:'Pontal do Paraná',uf:'PR',whatsapp:'41984616195',instagram:'w_sportbike',status:'Contatado',seller:'Thiago' },
  { nome:'Wings Wheels',cidade:'Cascavel',uf:'PR',whatsapp:'4588401661',instagram:'https://www.instagram.com/wingswheels.oficial/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'veloxbikeshop',cidade:'Curitiba',uf:'PR',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'vortixsap',cidade:'Santo Antônio da Platina',uf:'PR',status:'Contatado',seller:'Thiago' },
  { nome:'wehawk',cidade:'Maringá',uf:'PR',whatsapp:'44988115751',status:'Contatado',seller:'Thiago' },
  // ── RJ ───────────────────────────────────────────────────────────────────
  { nome:'Mundo Eletrico | Scooters e Bikes',cidade:'Nova Iguaçu',uf:'RJ',instagram:'mundoeletricomotors',status:'Prospecção',seller:'Leandro Araujo' },
  // ── RS ───────────────────────────────────────────────────────────────────
  { nome:'Benetti Bikes e Motos',cidade:'Capão da Canoa',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria ForBike Torres',cidade:'Torres',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Rio',cidade:'Rio Grande',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'BikeShop Torres',cidade:'Torres',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Gregor Technology',cidade:'Venancio Aires',uf:'RS',whatsapp:'51999528841',instagram:'https://www.instagram.com/gregor_technology/',status:'Prospecção',nota:'Excelente',seller:'Thiago' },
  { nome:'JETBIKE conserto de painéis e peças eletrônicas de motos.',cidade:'Porto Alegre',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'MB BikeShop',cidade:'Rio Grande',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'MOBI SCOOTERS E BIKES ELÉTRICAS',cidade:'Porto Alegre',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Mauro Bikes',cidade:'Porto Alegre',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Mobi.scooters',cidade:'Porto Alegre',uf:'RS',instagram:'mobi.scooters',status:'Prospecção',seller:'Thiago' },
  { nome:'Nathan Bicicletas',cidade:'Porto Alegre',uf:'RS',whatsapp:'51984752846',instagram:'https://www.instagram.com/nathanbicicletas/',status:'Prospecção',nota:'Excelente',seller:'Thiago' },
  { nome:'ORY (Volta E-Bike)',cidade:'Porto Alegre',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Over Bike',cidade:'Torres',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Pedala Torres - Aluguel de bicicleta',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Personal Biker',cidade:'Porto Alegre',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Scooters.com Porto Alegre',cidade:'Porto Alegre',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'ZERO CO2',cidade:'Rio Grande',uf:'RS',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  // ── SE ───────────────────────────────────────────────────────────────────
  { nome:'Aline Bicicletas',cidade:'São Domingos',uf:'SE',whatsapp:'79999990655',instagram:'https://www.instagram.com/alinebicicletas/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Do Charlito',cidade:'Nossa Sra. do Socorro',uf:'SE',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Aju Shop e Manutenção',cidade:'Aracaju',uf:'SE',whatsapp:'79998664200',instagram:'bikeajushop',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'CF Bike Shop',cidade:'Aracaju',uf:'SE',whatsapp:'79996703435',instagram:'cfbikeshop',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'Canindé de São Francisco',cidade:'Canindé de São Francisco',uf:'SE',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Ciclo Nutri Bike Shop',cidade:'Aracaju',uf:'SE',instagram:'ciclonutribikeshop',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'Ciclo Santos',cidade:'Nossa Senhora do Socorro',uf:'SE',whatsapp:'79988483820',instagram:'ciclosantos',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'Conection Bike Show',cidade:'Aracaju',uf:'SE',instagram:'_conectionbikeshow',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Conserta Bike Glória',cidade:'Nossa Senhora da Glória',uf:'SE',whatsapp:'7999489310',email:'nossasenhoradagloria@consertabike.com',instagram:'https://www.instagram.com/consertabikegloria/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Cunhadinho Bike Show',cidade:'Lagarto',uf:'SE',instagram:'cunhadinhobikeshow',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Doctor Bike',cidade:'Itabaiana',uf:'SE',whatsapp:'79998756839',instagram:'https://www.instagram.com/lojadoctorbike/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Estilo Bike',cidade:'Nossa Senhora do Socorro',uf:'SE',whatsapp:'79999432362',status:'Contatado',seller:'Thiago' },
  { nome:'Imperador das Bikes',cidade:'Nossa Senhora do Socorro',uf:'SE',whatsapp:'79981390437',instagram:'imperadorr_das_bikes',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Loja Júnior Bike',cidade:'Lagarto',uf:'SE',instagram:'loja_juniorbike',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'Magazine Bike Show (Revenda OGGI)',cidade:'Aracaju',uf:'SE',whatsapp:'79999432362',status:'Contatado',seller:'Thiago' },
  { nome:'Moto Ciclo Racing',cidade:'Itabaiana',uf:'SE',instagram:'motocicloracing',status:'Prospecção',seller:'Thiago' },
  { nome:'Novo Giro Bike Shop',cidade:'Aracaju',uf:'SE',instagram:'novogirobikeshop',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'Oliveer Bike Shop',cidade:'Tobias Barreto',uf:'SE',instagram:'https://www.instagram.com/oliveerbike_shop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Oximania Bike Sport',cidade:'Propriá',uf:'SE',email:'oximaniabikesport@gmail.com',instagram:'https://www.instagram.com/oximaniabikesport/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Pedala Mais - Bicicletaria',cidade:'Aracaju',uf:'SE',whatsapp:'79999577557',email:'comercial@pedalamais.com.br',instagram:'https://www.instagram.com/pedalamaisbicicletaria/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'R&E Bike',cidade:'Nossa Senhora da Glória',uf:'SE',instagram:'https://www.instagram.com/re.bike/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'RR Bike',cidade:'Aracaju',uf:'SE',instagram:'rr.bike',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'Sandro Motos Bikes',cidade:'Itabaiana',uf:'SE',whatsapp:'79996045285',instagram:'sandrobikes',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'Sport Bike Estância',cidade:'Estância',uf:'SE',whatsapp:'79998687405',instagram:'sportbikeestancia',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'Spot Bike',cidade:'Simão Dias',uf:'SE',instagram:'https://www.instagram.com/spot_bikee/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Stop Bike SE',cidade:'Lagarto',uf:'SE',whatsapp:'79999728577',instagram:'stopbike_se',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'Total Bike (Revenda OGGI)',cidade:'Itabaiana',uf:'SE',whatsapp:'79998092900',status:'Contatado',seller:'Thiago' },
  { nome:'Total Bike Shop',cidade:'Itabaiana',uf:'SE',instagram:'https://www.instagram.com/totalbikeshopita/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Watts Sergipe',cidade:'Aracaju',uf:'SE',whatsapp:'11991255637',instagram:'https://www.instagram.com/wattssergipe',status:'Contatado',nota:'Excelente',seller:'Thiago' },
  { nome:'Yossef Bike Show',cidade:'São Cristóvão',uf:'SE',instagram:'yossef_bike_show',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'ze grande ciclomotores',cidade:'Lagarto',uf:'SE',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  // ── SP ───────────────────────────────────────────────────────────────────
  { nome:'Bee Green Bikes',cidade:'Santos',uf:'SP',status:'Prospecção',nota:'Fraco' },
  { nome:'Bikemoto Bicicletas Eletricas',cidade:'São José do Rio Preto',uf:'SP',status:'Prospecção',nota:'Fraco' },
  { nome:'Scooter Elétrica MotoChefe Rio Preto',cidade:'São José do Rio Preto',uf:'SP',status:'Prospecção',nota:'Fraco' },
  // ── TO ───────────────────────────────────────────────────────────────────
  { nome:'A2 Bike Shop',cidade:'Palmas',uf:'TO',whatsapp:'6373214522',email:'a2bikeshop.palmas@gmail.com',instagram:'https://www.instagram.com/a2bikeshop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'A2 Bike Store',cidade:'Palmas',uf:'TO',instagram:'https://www.instagram.com/a2bikestore/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'AM Sport Bike',cidade:'Colinas do Tocantins',uf:'TO',instagram:'@Interior',status:'Contatado',seller:'Thiago' },
  { nome:'Aro Ciclo',cidade:'Palmas',uf:'TO',email:'arociclo@yahoo.com.br',instagram:'https://www.instagram.com/arociclo/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'BAISCON Moto Peças e Bikes',cidade:'Porto Nacional',uf:'TO',instagram:'https://www.instagram.com/baiscon.mb/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'BICICLETARIA & MOTO ALTO GIRO',cidade:'Miracema do Tocantins',uf:'TO',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicleta & Cia',cidade:'Gurupi',uf:'TO',whatsapp:'6333016260',email:'tocantinsbikes@gmail.com',instagram:'https://www.instagram.com/bicicletaeciagurupi/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Bicicletaria ZIG-BIN',cidade:'Palmas',uf:'TO',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletas & Companhia',cidade:'Gurupi',uf:'TO',whatsapp:'6333152001',email:'tocantinsbikes@gmail.com',instagram:'https://www.instagram.com/bicicletaeciagurupi/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletão Bike Shop (Revenda OGGI)',cidade:'Palmas',uf:'TO',whatsapp:'91983044984',status:'Contatado',seller:'Thiago' },
  { nome:'Bicicletão Bike Shop - Colinas',cidade:'Colinas do Tocantins',uf:'TO',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletão Bike Shop - Palmas',cidade:'Palmas',uf:'TO',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletão Bike Shop Araguaína',cidade:'Araguaína',uf:'TO',whatsapp:'6399281651',instagram:'https://www.instagram.com/bicicletaoaraguaina/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletão Moto Peças',cidade:'Araguaína',uf:'TO',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicimotos Peças',cidade:'Porto Nacional',uf:'TO',email:'thallesparanhos@hotmail.com',instagram:'https://www.instagram.com/bicimotospecas/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike Silva',cidade:'Araguaína',uf:'TO',whatsapp:'6399223273',instagram:'https://www.instagram.com/bikesilva.oficial/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bikes Aux',cidade:'Araguaína',uf:'TO',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'CICLOPALMAS',cidade:'Palmas',uf:'TO',instagram:'Capital',status:'Prospecção',seller:'Thiago' },
  { nome:"Camelo's Bike",cidade:'Palmas',uf:'TO',whatsapp:'63992858260',instagram:'https://www.instagram.com/camelosbike_pmw/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Casa Monark',cidade:'Miracema do Tocantins',uf:'TO',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'CiclomiX - Tocantins Bike',cidade:'Palmas',uf:'TO',email:'ciclomix.pmw@gmail.com',instagram:'https://www.instagram.com/ciclomix.pmw/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'DM Bikes',cidade:'Araguaína',uf:'TO',whatsapp:'63993009191',instagram:'https://www.instagram.com/dmbikesaux/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Dorian Bike Center',cidade:'Araguatins',uf:'TO',instagram:'@Interior',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Elite Bike Shop',cidade:'Palmas',uf:'TO',whatsapp:'6373215137',instagram:'https://www.instagram.com/elite_bike_shoppalmas/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Elite bike shoppalmas',cidade:'Palmas',uf:'TO',whatsapp:'556392903535',status:'Contatado',seller:'Thiago' },
  { nome:'Forum Bike',cidade:'Palmas',uf:'TO',whatsapp:'6373221637',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:"Giro Bike's",cidade:'Palmas',uf:'TO',whatsapp:'63992636599',instagram:'https://www.instagram.com/girobikes.pmw/',status:'Contatado',seller:'Thiago' },
  { nome:'Giro Bikes',cidade:'Palmas',uf:'TO',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'J Bike 122',cidade:'Palmas',uf:'TO',whatsapp:'63985170929',status:'Contatado',seller:'Thiago' },
  { nome:'L2 Bike Shop',cidade:'Gurupi',uf:'TO',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Mais Bicicletas',cidade:'Paraíso do Tocantins',uf:'TO',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Mais Mobility',cidade:'Palmas',uf:'TO',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:"Netto Bike's",cidade:'Gurupi',uf:'TO',whatsapp:'63992132709',status:'Contatado',seller:'Thiago' },
  { nome:'New Bike Palmas',cidade:'Palmas',uf:'TO',whatsapp:'63984004402',status:'Contatado',seller:'Thiago' },
  { nome:'Palmas Moto & Bike Shop',cidade:'Palmas',uf:'TO',whatsapp:'6373215150',status:'Contatado',seller:'Thiago' },
  { nome:'Pedal Ciclo',cidade:'Paraíso do Tocantins',uf:'TO',whatsapp:'6392367282',status:'Contatado',seller:'Thiago' },
  { nome:'Pedal Forte',cidade:'Palmas',uf:'TO',whatsapp:'6373215024',status:'Contatado',seller:'Thiago' },
  { nome:'REVOLT Mobilidade Sustentável',cidade:'Araguaína',uf:'TO',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Radical Bicicletas e Motos',cidade:'Miracema do Tocantins',uf:'TO',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Rafa Bike Shop',cidade:'Araguaína',uf:'TO',whatsapp:'63992711375',status:'Contatado',seller:'Thiago' },
  { nome:'Rota das Bike Shop',cidade:'Dianópolis',uf:'TO',whatsapp:'63992661222',instagram:'https://www.instagram.com/rotadasbikeshop/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Showbike Araguatins',cidade:'Araguatins',uf:'TO',instagram:'https://www.instagram.com/showbike.araguatins/',status:'Contatado',seller:'Thiago' },
  { nome:'Super Bike',cidade:'Palmas',uf:'TO',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'TREND BIKE MOTO',cidade:'Colinas do Tocantins',uf:'TO',instagram:'@Interior',status:'Prospecção',seller:'Thiago' },
  { nome:'Top Bike',cidade:'Gurupi',uf:'TO',whatsapp:'6373312240',status:'Contatado',seller:'Thiago' },
  // ── SC (sample — arquivo SC é muito grande, inserindo os mais relevantes) ──
  { nome:'ATACADAO DA SCOOTER',cidade:'Itajaí',uf:'SC',whatsapp:'4796856162',email:'flashveiculos8@gmail.com',instagram:'https://www.instagram.com/atacadaodascooteritajai/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Stop Bike',cidade:'Bombinhas',uf:'SC',whatsapp:'047997887569',instagram:'https://www.instagram.com/_stop_bike_/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike On',cidade:'Florianópolis',uf:'SC',whatsapp:'48992222200',email:'bionnutrimidias@gmail.com',instagram:'https://www.instagram.com/bikeonfloripa/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Suldailha Motos & Bikes',cidade:'Florianópolis',uf:'SC',email:'contato@suldailhamotos.com.br',instagram:'https://www.instagram.com/suldailha_motosbikes/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Autorizada Tui',cidade:'Balneário Camboriú',uf:'SC',instagram:'https://www.instagram.com/tui.balneariocamboriu/',status:'Contatado',nota:'Médio',seller:'Thiago' },
  { nome:'Itap Scooters Elétricas',cidade:'Itapema',uf:'SC',email:'itapbicicletaseletricas@gmail.com',instagram:'https://www.instagram.com/itapscooterseletricas/',status:'Contatado',nota:'Médio' },
  { nome:'E-Pulse Veículos Elétricos',cidade:'Criciúma',uf:'SC',whatsapp:'48992234004',instagram:'https://www.instagram.com/e_pulseofc/',status:'Prospecção',nota:'Excelente',seller:'Thiago' },
  { nome:'Luigi Scooters',cidade:'Florianópolis',uf:'SC',email:'luigi@luigi.eco.br',instagram:'https://www.instagram.com/luigiscooterseletricas/',status:'Prospecção',nota:'Excelente',seller:'Thiago' },
  { nome:'Oliver Scooters e Patinetes Eletricos',cidade:'Joinville',uf:'SC',whatsapp:'47991636110',instagram:'https://www.instagram.com/oliverscooters/',status:'Prospecção',nota:'Excelente',seller:'Thiago' },
  { nome:'Santa Bike',cidade:'Criciuma',uf:'SC',whatsapp:'48991195381',status:'Prospecção',nota:'Excelente',seller:'Thiago' },
  { nome:'Top Mobility Energy',cidade:'Criciuma',uf:'SC',whatsapp:'48991262878',instagram:'https://www.instagram.com/topmobilityenergy/',status:'Prospecção',nota:'Excelente',seller:'Thiago' },
  { nome:'Comercio Varejista de Bicicletas e Triciculos',cidade:'Barra Velha',uf:'SC',whatsapp:'48991056171',status:'Prospecção',nota:'Excelente',seller:'Thiago' },
  { nome:'Voltage Bikes',cidade:'Curitiba',uf:'SC',instagram:'https://www.instagram.com/voltagebikes/',status:'Prospecção',nota:'Excelente',seller:'Thiago' },
  { nome:'Área 85 Bikes',cidade:'Joinville',uf:'SC',whatsapp:'4799185233',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Âncora do Cação',cidade:'Bombinhas',uf:'SC',instagram:'ancoradocacao',status:'Contatado',seller:'Thiago' },
  { nome:'Batty Eletrobike',cidade:'Joinville',uf:'SC',whatsapp:'47997429008',instagram:'https://www.instagram.com/battyeletrobike/',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'Alex Bike',cidade:'Itajaí',uf:'SC',instagram:'https://www.instagram.com/alexbikeitj/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Alex Motos',cidade:'Balneário Camboriú',uf:'SC',whatsapp:'4788915390',email:'alexmotosbc@hotmail.com',instagram:'https://www.instagram.com/alexmotosbc/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Alves motos',cidade:'São Francisco do Sul',uf:'SC',whatsapp:'4799640773',instagram:'https://www.instagram.com/alves_moto/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Amazing Motos',cidade:'Joinville',uf:'SC',email:'vendasamazingmotos@gmail.com',instagram:'https://www.instagram.com/amazingmotos/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Assistência MOW',cidade:'Balneário Camboriú',uf:'SC',whatsapp:'48996636525',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bicicletaria Aquários',cidade:'Balneário Camboriú',uf:'SC',instagram:'https://www.instagram.com/bicicletariaaquarios/',status:'Contatado',nota:'Fraco',seller:'Thiago' },
  { nome:'Bike da ilha',cidade:'São Francisco do Sul',uf:'SC',instagram:'https://www.instagram.com/bikedailha.sfs/',status:'Contatado',seller:'Thiago' },
  { nome:'Monson',cidade:'Passo de Torres',uf:'SC',whatsapp:'4899805510',status:'Prospecção',seller:'Thiago' },
  { nome:'SS Imports',cidade:'Blumenau',uf:'SC',whatsapp:'47984439724',status:'Prospecção',seller:'Thiago' },
  { nome:'Eletric e-Bike',cidade:'Blumenau',uf:'SC',whatsapp:'47991518040',instagram:'https://www.instagram.com/eletricebike',status:'Prospecção',nota:'Fraco',seller:'Thiago' },
  { nome:'R1 Soluções em Transporte e Importações',cidade:'Joinville',uf:'SC',whatsapp:'47991761312',status:'Prospecção',seller:'Thiago' },
]

for (const c of clientes) {
  await ins(c)
}

// ── Resumo ────────────────────────────────────────────────────────────────────
const { rows: total } = await pool.query(
  'SELECT COUNT(*) as n FROM clients WHERE company_id=$1', [COMPANY_ID]
)
console.log(`\n✅ Pronto. Inseridos: ${inserted} | Já existiam: ${skipped}`)
console.log(`   Total de clientes na Atomi agora: ${total[0].n}`)
await pool.end()
